### ISSUE TITLE
AppObjectID vs SP ID

### ISSUE THREAD

**Issue by msghaleb** [vplauzon/aks#1]
First of all, great post and very nice presentation of a point where many would profit from.

One small remark, may be some other guys will find it useful too (more on the documentation side)

The Application ID is clear, this is the one in the portal, however the Object ID in the portal is the Object ID of the application not the Object ID of the service principal. For the ARM Template to work we will need the SP ID.

Using PowerShell: Get-AzureRMADServicePrincipal -SearchString "AppName"

To get the Application ID: Get-AzureRmADApplication -DisplayNameStartWith "AppName"

Again great work, many thanks!

MG

**Comment by vplauzon** [comment]
Hi Mohamed,


Thanks for the feedback!

Would you mind posting it as a comment on the blog post?  This way readers can have access to it?



Cheers & Thank you for contributing!
